# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Shaowei's Blog
tagline:          'The personal website of Shaowei Ling'
description:      'The personal website of Shaowei Ling'
url:              http://lingshaowei.github.io
paginate:         1
baseurl:          /
author:
  name:           Shaowei Ling
  url:            
  email:          lingshaowei@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/lingshaowei/lingshaowei.github.io

# Navigation bar
pages_list:       {'Archive': '/archive','About': '/about','Feed': '/atom.xml'}
